from pathlib import Path

REQUIRED_STRUCTURE = [
    "config",
    "data",
    "data/market_fetcher.py",
    "strategies",
    "indicators",
    "ai",
    "filters",
    "telegram",
    "dashboard",
    "webhooks",
    "scripts",
]

class SentinelRebuilderAgent:
    def rebuild(self, root):
        root = Path(root)

        for item in REQUIRED_STRUCTURE:
            path = root / item

            if "." in path.name:
                path.parent.mkdir(parents=True, exist_ok=True)
                if not path.exists():
                    path.write_text(self.stub(path))
            else:
                path.mkdir(parents=True, exist_ok=True)

        self.fix_init_files(root)

    def fix_init_files(self, root):
        for folder in root.rglob("*"):
            if folder.is_dir():
                init = folder / "__init__.py"
                if not init.exists():
                    init.write_text("")

    def stub(self, path):
        return f'''"""
AUTO-GENERATED BY SENTINEL SYNTHETIC ENGINE
FILE: {path.name}
"""

def placeholder():
    return True
'''
